'use client';
import { useEffect, useState } from 'react';
import { Box, Layers, HardDrive, ArrowUpRight, ArrowRight, RefreshCw, Search, Plus, Server, CircleHelp, Play, Pause, Square, ChevronRight, Check, Zap, Package, Network, Activity } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';

type Container = {name:string; image:string; group:string; state:string; ports:string[][]; color:string; letter:string; update:boolean; memory:string};
const initial:Container[] = [
{name:'nginx-proxy',image:'nginx:latest',group:'web-services',state:'运行中',ports:[['8080','80','TCP'],['8443','443','TCP']],color:'green',letter:'N',update:true,memory:'24.6 MB'},
{name:'immich-server',image:'ghcr.io/immich-app/immich-server:latest',group:'immich',state:'运行中',ports:[['2283','2283','TCP']],color:'blue',letter:'I',update:true,memory:'386 MB'},
{name:'redis',image:'redis:latest',group:'web-services',state:'运行中',ports:[['6379','6379','TCP']],color:'red',letter:'R',update:true,memory:'12.8 MB'},
{name:'jellyfin',image:'jellyfin/jellyfin:latest',group:'media',state:'运行中',ports:[['8096','8096','TCP'],['7359','7359','UDP']],color:'purple',letter:'J',update:false,memory:'218 MB'},
{name:'postgres',image:'postgres:16-alpine',group:'immich',state:'运行中',ports:[],color:'blue',letter:'P',update:false,memory:'84.2 MB'},
{name:'syncthing',image:'syncthing/syncthing:latest',group:'独立容器',state:'已暂停',ports:[['8384','8384','TCP']],color:'cyan',letter:'S',update:false,memory:'46.1 MB'},
{name:'test-nginx',image:'nginx:1.26',group:'独立容器',state:'已停止',ports:[['8088','80','TCP']],color:'gray',letter:'N',update:false,memory:'—'}];
const navigation=[{label:'容器管理',icon:Box},{label:'镜像管理',icon:HardDrive},{label:'Compose 项目',icon:Layers},{label:'加速源配置',icon:Zap}];
export default function Home(){
const [page,setPage]=useState('容器管理');const [items,setItems]=useState(initial);const [query,setQuery]=useState('');const [filter,setFilter]=useState('全部');const [checking,setChecking]=useState(true);const [checked,setChecked]=useState('');const [modal,setModal]=useState<{kind:string;name:string}|null>(null);const [notice,setNotice]=useState('');const [project,setProject]=useState('');const [compose,setCompose]=useState('services:\n  nginx:\n    image: nginx:latest\n    ports:\n      - "8080:80"\n    restart: unless-stopped');const [mirrors,setMirrors]=useState('https://mirror.example.com');const [projects,setProjects]=useState(['web-services','immich','media']);
useEffect(()=>{const t=setTimeout(()=>{setChecking(false);setChecked('刚刚');},1200);return()=>clearTimeout(t)},[]);
useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)}},[notice]);
useEffect(()=>{
const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
if(!context?.registerTool)return;
const lifecycle=new AbortController();
try{Promise.resolve(context.registerTool({name:'list_demo_containers',description:'Read containers and latest image update status in this UI prototype. These are demonstration data, not a real Docker host.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {demo:true,containers:items}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
return()=>lifecycle.abort();
},[items]);
const updates=items.filter(i=>i.update);const running=items.filter(i=>i.state==='运行中').length;
function check(){setChecking(true);setTimeout(()=>{setChecking(false);setChecked('刚刚');setNotice('检查完成：仅检查 latest 标签（演示）')},1000)}
function action(name:string,state:string){setItems(a=>a.map(i=>i.name===name?{...i,state}:i));setNotice(`${name} ${state}（演示）`)}
function confirm(){if(!modal)return;if(modal.kind==='upgrade'){setItems(a=>a.map(i=>modal.name==='全部'||i.name===modal.name?{...i,update:false}:i));setNotice('镜像升级演示完成，容器配置与端口映射保留')}else if(modal.kind==='compose'){if(!project.trim()||!compose.includes('services:'))return;setProjects(a=>[...a,project.trim()]);setNotice('Compose 项目已添加（演示）');setProject('')}else if(modal.kind==='restart'){action(modal.name,'运行中')}setModal(null)}
const visible=items.filter(i=>(filter==='全部'||i.state===filter)&&(i.name+' '+i.image+' '+i.group).toLowerCase().includes(query.toLowerCase()));
return <div className="app-shell">
<aside className="sidebar"><a className="brand" href="/" aria-label="NasDocker 首页"><span className="brand-icon"><Box size={24}/></span><span>nas<span className="brand-light">docker</span><small>HOST CONTROL CENTER</small></span></a><div className="workspace"><span className="host-icon"><Server size={18}/></span><div><b>我的 NAS</b><small>本地 Docker 环境</small></div><span className="online-dot"/></div><p className="nav-label">工作空间</p><nav>{navigation.map(n=><button key={n.label} className={'nav-item '+(page===n.label?'active':'')} onClick={()=>{setPage(n.label);setQuery('')}}><n.icon size={19}/><span>{n.label}</span>{n.label==='容器管理'&&<span className="nav-count">{items.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="connection"><span className="online-dot"/>Docker 引擎已连接<small>v27.5.1 · linux / amd64</small></div><button className="help" onClick={()=>setModal({kind:'help',name:''})}><CircleHelp size={17}/>使用说明<ArrowUpRight size={15}/></button><div className="profile"><span className="avatar">A</span><div><b>Administrator</b><small>本地管理员</small></div></div></div></aside>
<div className="main-shell"><header className="topbar"><div>工作空间 <ChevronRight size={14}/> <span>{page}</span></div><div><span className="demo-label">UI 交互原型</span><span className="top-host"><span className="online-dot"/>nas-home</span></div></header>
<main><div className="page-heading"><div><div className="eyebrow">DOCKER WORKSPACE</div><h1>{page}</h1><p>{page==='容器管理'?'掌握每一个服务的状态，让管理更简单。':page==='镜像管理'?'查看本地镜像，及时发现 latest 标签更新。':page==='Compose 项目'?'用一份配置，管理一组服务。':'管理宿主机 Docker 的镜像拉取加速源。'}</p></div><Button className="primary-button" onClick={()=>setModal({kind:'compose',name:''})}><Plus/>部署 Compose</Button></div>
{page==='容器管理'&&<><section className="metrics"><Metric icon={<Box/>} label="全部容器" value={items.length} detail="当前宿主机"/><Metric icon={<Activity/>} label="运行中" value={running} detail="服务运行正常" green/><Metric icon={<Pause/>} label="暂停 / 停止" value={items.length-running} detail="可随时恢复"/><Metric icon={<Package/>} label="可升级镜像" value={checking?'—':updates.length} detail="仅检查 latest" blue/></section>
<section className="updates-panel"><div className="section-line"><div className="section-title"><span className="update-symbol"><ArrowUpRight size={20}/></span><h2>{checking?'正在检查镜像更新':updates.length?'发现可升级镜像':'latest 镜像均为最新'}</h2><span className="count-badge">{checking?'…':updates.length}</span></div><button className="text-button" disabled={checking} onClick={check}><RefreshCw size={14} className={checking?'spin':''}/>{checking?'检查中':'重新检查'}</button></div><p className="section-description">对比正在使用的镜像与远端 latest 内容，升级将重建对应容器。</p><div className="update-cards">{updates.map(i=><article className="update-card" key={i.name}><div className={'app-icon '+i.color}>{i.letter}</div><div className="update-info"><b>{i.image.split(':')[0].split('/').pop()}<span className="tag">latest</span></b><small>关联容器：{i.name}</small></div><button disabled={checking} className="update-action" onClick={()=>setModal({kind:'upgrade',name:i.name})}>升级<ArrowUpRight size={14}/></button></article>)}{updates.length===0&&<p className="success-inline"><Check size={17}/>所有 latest 镜像已完成更新</p>}</div><div className="update-foot"><span><span className="online-dot"/>自动检查已开启 · {checking?'正在连接镜像仓库':`上次检查：${checked}`}</span><span>非 latest 标签不参与检查</span></div></section>
<section className="container-panel"><div className="list-heading"><div className="section-title"><h2>容器列表</h2><span className="muted">{items.length} 个容器</span></div><div className="search"><Search size={16}/><Input aria-label="搜索容器或镜像" placeholder="搜索容器、镜像或项目…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="filter-line"><div className="filters">{['全部','运行中','已暂停','已停止'].map(s=><button key={s} onClick={()=>setFilter(s)} className={filter===s?'selected':''}>{s}<span>{s==='全部'?items.length:items.filter(i=>i.state===s).length}</span></button>)}</div><span className="port-legend"><Network size={14}/>宿主机端口 <ArrowRight size={13}/> 容器端口</span></div><div className="table-scroll"><table><thead><tr><th>容器 / 镜像</th><th>状态</th><th>端口映射 <span className="th-sub">宿主机 → 容器</span></th><th>Compose 项目</th><th>内存</th><th className="right">操作</th></tr></thead><tbody>{visible.map(i=><tr key={i.name}><td><div className="container-name"><div className={'app-icon small '+i.color}>{i.letter}</div><div><b>{i.name}{i.update&&!checking&&<span className="update-dot" title="镜像可升级"/>}</b><small title={i.image}>{i.image}</small></div></div></td><td><span className={'status '+(i.state==='运行中'?'running':i.state==='已暂停'?'paused':'stopped')}><i/>{i.state}</span></td><td><div className="ports">{i.ports.length?i.ports.map((p,k)=><div className="port-pair" key={k}><code>{p[0]}</code><ArrowRight size={13}/><code>{p[1]}</code><span>{p[2]}</span></div>):<span className="muted">未映射</span>}</div></td><td><span className="project-label">{i.group!=='独立容器'&&<Layers size={13}/>} {i.group}</span></td><td className="memory">{i.memory}</td><td><div className="row-actions">{i.state==='运行中'?<><IconButton label={`暂停 ${i.name}`} onClick={()=>action(i.name,'已暂停')}><Pause/></IconButton><IconButton label={`停止 ${i.name}`} onClick={()=>action(i.name,'已停止')}><Square/></IconButton></>:<IconButton label={`启动或恢复 ${i.name}`} onClick={()=>action(i.name,'运行中')}><Play/></IconButton>}<IconButton label={`重启 ${i.name}`} onClick={()=>setModal({kind:'restart',name:i.name})}><RefreshCw/></IconButton></div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">没有匹配的容器，请调整搜索或筛选条件。</div>}</div><div className="table-footer">显示 {visible.length} / {items.length} 个容器<span><span className="online-dot"/>已同步宿主机状态 · 演示数据</span></div></section></>}
{page==='镜像管理'&&<section className="container-panel"><div className="list-heading"><h2>本地镜像 <span className="muted">{items.length}</span></h2><Button variant="outline" onClick={check}><RefreshCw className={checking?'spin':''}/>{checking?'检查中':'检查 latest 更新'}</Button></div><div className="image-list">{items.map(i=><div className="image-row" key={i.name}><div className={'app-icon '+i.color}>{i.letter}</div><div className="grow"><b>{i.image}</b><small>使用容器：{i.name}</small></div><span className="muted">{!i.image.endsWith(':latest')?'不参与更新检查':checking?'检查中':i.update?'有更新可用':'已是最新'}</span>{i.update&&<Button variant="outline" disabled={checking} onClick={()=>setModal({kind:'upgrade',name:i.name})}>升级镜像</Button>}</div>)}</div></section>}
{page==='Compose 项目'&&<div className="compose-grid">{projects.map((p,index)=><section className="compose-card" key={p+index}><div className="compose-icon"><Layers/></div><span className="status running"><i/>已部署</span><h2>{p}</h2><p>{items.filter(i=>i.group===p).length} 个容器 · Docker Compose</p><div className="compose-services">{items.filter(i=>i.group===p).map(i=><span key={i.name}><span className="online-dot"/>{i.name} · {i.state}</span>)}</div><div className="compose-actions"><Button variant="outline" onClick={()=>{setProject(p);setModal({kind:'view',name:p})}}>查看配置</Button><Button variant="ghost" onClick={()=>{setItems(a=>a.map(i=>i.group===p?{...i,state:'已停止'}:i));setNotice(`${p} 已停止（演示）`)}}>停止项目</Button></div></section>)}</div>}
{page==='加速源配置'&&<section className="settings-panel"><div className="section-title"><Zap/><h2>镜像加速源</h2></div><p>按顺序填写加速源地址，每行一个。</p><label htmlFor="mirrors">Registry mirrors</label><Textarea id="mirrors" rows={6} value={mirrors} onChange={e=>setMirrors(e.target.value)} className="config-input"/><div className="setting-note"><CircleHelp size={18}/><span>保存后需应用到宿主机 Docker。此原型仅演示配置流程，示例地址不可用。</span></div><Button onClick={()=>{try{mirrors.split('\n').filter(Boolean).forEach(s=>{if(new URL(s).protocol!=='https:')throw Error()});setNotice('配置已保存到当前演示页面，尚未应用到宿主机')}catch{setNotice('请填写有效的 HTTPS 加速源地址')}}}>保存配置</Button></section>}
<footer className="main-footer"><span><Server size={14}/>nas-home <span className="divider">/</span>192.168.1.100</span><span>NasDocker <span className="divider">·</span> 每一个容器，井然有序。</span></footer></main></div>
<Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="operation-dialog"><DialogTitle>{modal?.kind==='upgrade'?'升级镜像':modal?.kind==='compose'?'部署 Compose':modal?.kind==='view'?'Compose 配置':modal?.kind==='restart'?'重启容器':'关于此原型'}</DialogTitle><DialogDescription>{modal?.kind==='upgrade'?`将拉取 ${items.find(i=>i.name===modal.name)?.image} 并重建 ${modal.name}。`:modal?.kind==='restart'?`重启 ${modal.name} 会短暂中断服务。`:'当前是 UI 交互原型，所有操作使用演示数据，不连接真实宿主机。'}</DialogDescription>{modal?.kind==='upgrade'&&<div className="confirm-info"><p><Check size={16}/>保留端口、环境变量与数据挂载</p><p><Layers size={16}/>Compose 容器通过所属项目更新</p><p><Activity size={16}/>更新期间服务会短暂中断</p></div>}{(modal?.kind==='compose'||modal?.kind==='view')&&<><label htmlFor="project">项目名称</label><Input id="project" value={project} readOnly={modal.kind==='view'} onChange={e=>setProject(e.target.value)} placeholder="例如：my-services"/><label htmlFor="compose">{modal.kind==='view'?'配置示例（非实际项目配置）':'compose.yaml'}</label><Textarea id="compose" className="code-editor" rows={9} value={compose} readOnly={modal.kind==='view'} onChange={e=>setCompose(e.target.value)}/></>}{modal?.kind==='help'&&<p>可切换四个管理页面，体验镜像升级、容器启停与暂停、Compose 部署及加速源配置。刷新页面将恢复演示数据。</p>}<DialogFooter><Button variant="outline" onClick={()=>setModal(null)}>关闭</Button>{['upgrade','compose','restart'].includes(modal?.kind||'')&&<Button disabled={modal?.kind==='compose'&&(!project.trim()||!compose.includes('services:'))} onClick={confirm}>{modal?.kind==='upgrade'?'确认升级':modal?.kind==='restart'?'确认重启':'部署项目'}</Button>}</DialogFooter></DialogContent></Dialog>
{notice&&<div className="notice" role="status"><Check size={17}/>{notice}</div>}
</div>}
function Metric({icon,label,value,detail,green,blue}:{icon:React.ReactNode;label:string;value:string|number;detail:string;green?:boolean;blue?:boolean}){return <article className={'metric '+(green?'green-metric':blue?'blue-metric':'')}><div><span>{label}</span>{icon}</div><strong>{value}<small>个</small></strong><p>{green&&<span className="online-dot"/>}{detail}</p></article>}
function IconButton({label,onClick,children}:{label:string;onClick:()=>void;children:React.ReactNode}){return <Button variant="ghost" size="icon" aria-label={label} title={label} onClick={onClick}>{children}</Button>}
